# Generated by Django 5.0.2 on 2024-03-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_sample_githublink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='githublink',
            field=models.URLField(default='#'),
        ),
    ]
