# Generated by Django 5.0.2 on 2024-03-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='day_def',
            field=models.CharField(default='17', max_length=20),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='month_def',
            field=models.CharField(default='اسفند', max_length=20),
        ),
    ]
