# Generated by Django 5.0.2 on 2024-03-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_post_day_def_blog_post_month_def'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='randomkey',
            field=models.CharField(default=2028, max_length=5),
        ),
    ]
