# Generated by Django 5.0.2 on 2024-03-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_post_randomkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='randomkey',
            field=models.CharField(default=2052, max_length=5),
        ),
    ]
