# Generated by Django 5.0.2 on 2024-03-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_post_randomkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='randomkey',
            field=models.CharField(default=2011, max_length=5),
        ),
    ]
