# Generated by Django 5.0.2 on 2024-03-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=30)),
                ('instagram', models.CharField(max_length=200, null=True)),
                ('facebook', models.CharField(max_length=200, null=True)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('BirthdayDate', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('BirthdayPlace', models.CharField(max_length=40)),
            ],
        ),
    ]
