# Generated by Django 5.0.2 on 2024-03-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerinfo',
            name='job',
            field=models.CharField(default='null', max_length=40),
            preserve_default=False,
        ),
    ]
