# Generated by Django 5.0.2 on 2024-03-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutme_whattodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whattodo',
            name='logo',
        ),
    ]
