# Generated by Django 5.0.2 on 2024-03-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_whattodo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='whattodo',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
