# Generated by Django 5.0.2 on 2024-03-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_whattodo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whattodo',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
