# Generated by Django 5.0.2 on 2024-03-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_rename_image_whattodo_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whattodo',
            name='img',
        ),
    ]
