# Generated by Django 5.0.2 on 2024-03-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_whattodo_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='whattodo',
            name='img',
            field=models.ImageField(default=True, upload_to='media'),
        ),
    ]
