# Generated by Django 5.0.2 on 2024-03-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_comments_alter_whattodo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='profile',
            field=models.ImageField(default=False, upload_to='media/'),
        ),
    ]
