# Generated by Django 5.0.2 on 2024-03-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_comments_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerinfo',
            name='Profile',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
