# Generated by Django 5.0.2 on 2024-03-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_headerinfo_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerinfo',
            name='Profile',
        ),
    ]
